/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BTL;

import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author txdao
 */
public class FBangDiem extends javax.swing.JFrame implements Serializable{
    public String fileName = "HocPhan.txt";
    public String fileName2 = "BangDiem.txt";
    public String fileName3 = "DSSinhVien.txt";
    public String fileName4 = "taikhoan.txt";

    public DBEngine db = new DBEngine();
    public ArrayList<Diem> bangDiem = new ArrayList<>();
    public ArrayList<SinhVien> dssv = new ArrayList<>();
    public ArrayList<TaiKhoan> dstk = new ArrayList<>();
    /**
     * Creates new form FBangDiem
     */
    public FBangDiem() {
        try{
            bangDiem = (ArrayList<Diem>) db.docFile(fileName2);
            dssv = (ArrayList<SinhVien>) db.docFile(fileName3);
            dstk = (ArrayList<TaiKhoan>) db.docFile(fileName4);
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(rootPane, E.toString());
        }
        initComponents();
        this.setEnabled(true);
        this.setLocationRelativeTo(null);
        this.JTable.setEnabled(false);
        this.JTable.setAutoCreateRowSorter(true);
        MainFrame main = new MainFrame();
        for(int i=0;i<dstk.size();i++){
            if(dssv.get(i).tk.user.compareTo(main.user) == 0){
                bangDiem = dssv.get(i).BD;
                break;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Commons", 1, 18)); // NOI18N
        jLabel1.setText("Bang Diem");

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {bangDiem.get(0).x.name, bangDiem.get(0).D10(), bangDiem.get(0).D4(), bangDiem.get(0).Dchar()},
                {bangDiem.get(1).x.name, bangDiem.get(1).D10(), bangDiem.get(1).D4(), bangDiem.get(1).Dchar()},
                {bangDiem.get(2).x.name, bangDiem.get(2).D10(), bangDiem.get(2).D4(), bangDiem.get(2).Dchar()},
                {bangDiem.get(3).x.name, bangDiem.get(3).D10(), bangDiem.get(3).D4(), bangDiem.get(3).Dchar()},
                {bangDiem.get(4).x.name, bangDiem.get(4).D10(), bangDiem.get(4).D4(), bangDiem.get(4).Dchar()},
                {bangDiem.get(5).x.name, bangDiem.get(5).D10(), bangDiem.get(5).D4(), bangDiem.get(5).Dchar()},
                {bangDiem.get(6).x.name, bangDiem.get(6).D10(), bangDiem.get(6).D4(), bangDiem.get(6).Dchar()},
                {bangDiem.get(7).x.name, bangDiem.get(7).D10(), bangDiem.get(7).D4(), bangDiem.get(7).Dchar()},
                {bangDiem.get(8).x.name, bangDiem.get(8).D10(), bangDiem.get(8).D4(), bangDiem.get(8).Dchar()},
                {bangDiem.get(9).x.name, bangDiem.get(9).D10(), bangDiem.get(9).D4(), bangDiem.get(9).Dchar()}
            },
            new String [] {
                "Hoc Phan", "Diem 10", "Diem 4", "Diem chu"
            }
        ));
        jScrollPane1.setViewportView(JTable);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FBangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FBangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FBangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FBangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FBangDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
