/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BTL;

import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author txdao
 */
public class FBangDiemGV extends javax.swing.JFrame implements Serializable{
    public String fileName = "HocPhan.txt";
    public String fileName2 = "BangDiem.txt";
    public DBEngine db = new DBEngine();
    public ArrayList<Diem> bangDiem = new ArrayList<>();
    public Diem diem = new Diem();
    /**
     * Creates new form FBangDiem
     */
    public FBangDiemGV() {
        try{
            bangDiem = (ArrayList<Diem>) db.docFile(fileName2);
            
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(rootPane, E.toString());
        }
        initComponents();
        this.setEnabled(true);
        this.setLocationRelativeTo(null);
        this.JTable.setEnabled(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        L1 = new javax.swing.JTextField();
        L2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        L3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        suaButton = new javax.swing.JButton();

        jTextField3.setText("jTextField1");

        jLabel4.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Commons", 1, 18)); // NOI18N
        jLabel1.setText("Bang Diem");

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {bangDiem.get(0).x.name, bangDiem.get(0).D10(), bangDiem.get(0).D4(), bangDiem.get(0).Dchar()},
                {bangDiem.get(1).x.name, bangDiem.get(1).D10(), bangDiem.get(1).D4(), bangDiem.get(1).Dchar()},
                {bangDiem.get(2).x.name, bangDiem.get(2).D10(), bangDiem.get(2).D4(), bangDiem.get(2).Dchar()},
                {bangDiem.get(3).x.name, bangDiem.get(3).D10(), bangDiem.get(3).D4(), bangDiem.get(3).Dchar()},
                {bangDiem.get(4).x.name, bangDiem.get(4).D10(), bangDiem.get(4).D4(), bangDiem.get(4).Dchar()},
                {bangDiem.get(5).x.name, bangDiem.get(5).D10(), bangDiem.get(5).D4(), bangDiem.get(5).Dchar()},
                {bangDiem.get(6).x.name, bangDiem.get(6).D10(), bangDiem.get(6).D4(), bangDiem.get(6).Dchar()},
                {bangDiem.get(7).x.name, bangDiem.get(7).D10(), bangDiem.get(7).D4(), bangDiem.get(7).Dchar()},
                {bangDiem.get(8).x.name, bangDiem.get(8).D10(), bangDiem.get(8).D4(), bangDiem.get(8).Dchar()},
                {bangDiem.get(9).x.name, bangDiem.get(9).D10(), bangDiem.get(9).D4(), bangDiem.get(9).Dchar()}
            },
            new String [] {
                "Hoc Phan", "Diem 10", "Diem 4", "Diem chu"
            }
        ));
        JTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("L1");

        jLabel3.setText("L2");

        jLabel5.setText("L3");

        suaButton.setText("Sua");
        suaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(suaButton))))
                    .addComponent(jLabel3))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(suaButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void suaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaButtonActionPerformed
        if(this.JTable.getSelectedColumn() == -1){
            JOptionPane.showMessageDialog(rootPane, "Chon 1 hoc phan!");
            return;
        }
        try{
            bangDiem = (ArrayList<Diem>)db.docFile(fileName2);
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(rootPane, E.toString());
        }
        int k = this.JTable.getSelectedRow();

        diem = bangDiem.get(k);
        float dl1,dl2,dl3;
        dl1 = Float.parseFloat(L1.getText());
        dl2 = Float.parseFloat(L2.getText());
        dl3 = Float.parseFloat(L3.getText());
        if(dl1 < 0 || dl1 >10){
            JOptionPane.showMessageDialog(rootPane, "L1 khong hop le!");
            return;
        }
        if(dl2 < 0 || dl2 >10){
            JOptionPane.showMessageDialog(rootPane, "L2 khong hop le!");
            return;
        }
        if(dl3 < 0 || dl3 >10){
            JOptionPane.showMessageDialog(rootPane, "L3 khong hop le!");
            return;
        }
        int s=1;
        int input = JOptionPane.showConfirmDialog(rootPane, "Chac chan sua!","Warning",s);
        if(input == 0){
            diem.L1 = dl1;
            diem.L2 = dl2;
            diem.L3 = dl3;
            bangDiem.set(k, diem);
            try{
                db.LuuFile(fileName2, bangDiem);
                JOptionPane.showMessageDialog(rootPane, "Sua thanh cong");
                this.setVisible(false);
                FBangDiemGV newBD = new FBangDiemGV();
                newBD.setVisible(true);
            }
            catch(Exception E){
                JOptionPane.showMessageDialog(rootPane, E);
            }
        }
    }//GEN-LAST:event_suaButtonActionPerformed

    private void JTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableMouseClicked
        try{
            bangDiem = (ArrayList<Diem>)db.docFile(fileName2);
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(rootPane, E.toString());
        }
        int k = this.JTable.getSelectedRow();
        if(this.JTable.getSelectedRow() == -1){
            return;
        }
        else{

            diem = bangDiem.get(k);
            L1.setText(String.valueOf(diem.L1));
            L2.setText(String.valueOf(diem.L2));
            L3.setText(String.valueOf(diem.L3));
        }
    }//GEN-LAST:event_JTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FBangDiemGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FBangDiemGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FBangDiemGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FBangDiemGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FBangDiemGV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JTextField L1;
    private javax.swing.JTextField L2;
    private javax.swing.JTextField L3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton suaButton;
    // End of variables declaration//GEN-END:variables
}
