/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BTL;

import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author txdao
 */
public class FDSHoTro extends javax.swing.JFrame {
    static SinhVien sv = new SinhVien();
    static String fileName = "DSHoTro.txt";
    static DBEngine db = new DBEngine();
    static ArrayList<HoTro> dsht = new ArrayList<>();
    /**
     * Creates new form FDSHoTro
     */
    public FDSHoTro() {
        initComponents();
        this.setLocationRelativeTo(null);
        MainFrame main = new MainFrame();
        if(main.userKind !=1){
            jButton1.setEnabled(false);
        }
        Label1.setCursor(new Cursor(12) {
        });
        Label2.setCursor(new Cursor(12) {
        });
        Label3.setCursor(new Cursor(12) {
        });
        Label4.setCursor(new Cursor(12) {
        });
        Label5.setCursor(new Cursor(12) {
        });
        Label6.setCursor(new Cursor(12) {
        });
        Label7.setCursor(new Cursor(12) {
        });
        try{
            dsht = (ArrayList<HoTro>) db.docFile(fileName);
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(rootPane, E);
        }
        if(dsht.size() < 1){
            Label1.setText("Chua co yeu cau nao");
            Label2.setVisible(false);
            Label3.setVisible(false);
            Label4.setVisible(false);
            Label5.setVisible(false);
            Label6.setVisible(false);
            Label7.setVisible(false);

        }
        if(dsht.size() == 1){
            Label1.setText(dsht.get(0).thongTinHT);
            Label2.setVisible(false);
            Label3.setVisible(false);
            Label4.setVisible(false);
            Label5.setVisible(false);
            Label6.setVisible(false);
            Label7.setVisible(false);
        }
        if(dsht.size() == 2){
            Label1.setText(dsht.get(0).thongTinHT);
            Label2.setText(dsht.get(1).thongTinHT);
            Label3.setVisible(false);
            Label4.setVisible(false);
            Label5.setVisible(false);
            Label6.setVisible(false);
            Label7.setVisible(false);

        }
        if(dsht.size() == 3){
            Label1.setText(dsht.get(0).thongTinHT);
            Label2.setText(dsht.get(1).thongTinHT);
            Label3.setText(dsht.get(2).thongTinHT);
            Label4.setVisible(false);
            Label5.setVisible(false);
            Label6.setVisible(false);
            Label7.setVisible(false);
        }
        if(dsht.size() == 4){
            Label1.setText(dsht.get(0).thongTinHT);
            Label2.setText(dsht.get(1).thongTinHT);
            Label3.setText(dsht.get(2).thongTinHT);
            Label4.setText(dsht.get(3).thongTinHT);
            Label5.setVisible(false);
            Label6.setVisible(false);
            Label7.setVisible(false);
        }
        if(dsht.size() == 5){
            Label1.setText(dsht.get(0).thongTinHT);
            Label2.setText(dsht.get(1).thongTinHT);
            Label3.setText(dsht.get(2).thongTinHT);
            Label4.setText(dsht.get(3).thongTinHT);
            Label5.setText(dsht.get(4).thongTinHT);
            Label6.setVisible(false);
            Label7.setVisible(false);
        }
        if(dsht.size() == 6){
            Label1.setText(dsht.get(0).thongTinHT);
            Label2.setText(dsht.get(1).thongTinHT);
            Label3.setText(dsht.get(2).thongTinHT);
            Label4.setText(dsht.get(3).thongTinHT);
            Label5.setText(dsht.get(4).thongTinHT);
            Label6.setText(dsht.get(5).thongTinHT);
            Label7.setVisible(false);
        }
        if(dsht.size() == 6){
            Label1.setText(dsht.get(0).thongTinHT);
            Label2.setText(dsht.get(1).thongTinHT);
            Label3.setText(dsht.get(2).thongTinHT);
            Label4.setText(dsht.get(3).thongTinHT);
            Label5.setText(dsht.get(4).thongTinHT);
            Label6.setText(dsht.get(5).thongTinHT);
            Label7.setText(dsht.get(6).thongTinHT);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Danh sach ho tro");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        Label1.setText("jLabel2");
        Label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label1MouseClicked(evt);
            }
        });

        Label2.setText("jLabel2");
        Label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label2MouseClicked(evt);
            }
        });

        Label3.setText("jLabel2");
        Label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label3MouseClicked(evt);
            }
        });

        Label6.setText("jLabel2");
        Label6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label6MouseClicked(evt);
            }
        });

        Label5.setText("jLabel2");
        Label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label5MouseClicked(evt);
            }
        });

        Label4.setText("jLabel2");
        Label4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label4MouseClicked(evt);
            }
        });

        Label7.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Label6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(Label5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label2)
                .addGap(12, 12, 12)
                .addComponent(Label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label5)
                .addGap(12, 12, 12)
                .addComponent(Label6)
                .addGap(16, 16, 16)
                .addComponent(Label7)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButton1.setText("Tao moi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thoat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jButton1)
                .addGap(44, 44, 44)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FHoTro HT = new FHoTro();
        if(dsht.size()>=7){
            JOptionPane.showMessageDialog(rootPane, "Ban da dat toi da so yeu cau!");
            return;
        }
            HT.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label1MouseClicked
        HoTro hoTro = new HoTro();
        hoTro = dsht.get(0);
        PhanHoi phanHoi = new PhanHoi();
        phanHoi.F1.setText(dsht.get(0).x.name);
        phanHoi.F3.setText(dsht.get(0).x.id);
        phanHoi.F4.setText(dsht.get(0).x.name);
        phanHoi.F5.setText(dsht.get(0).x.name);
        phanHoi.setVisible(true);
    }//GEN-LAST:event_Label1MouseClicked

    private void Label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label2MouseClicked
        HoTro hoTro = new HoTro();
        hoTro = dsht.get(0);
        PhanHoi phanHoi = new PhanHoi();
        phanHoi.F1.setText(dsht.get(1).x.name);
        phanHoi.F3.setText(dsht.get(1).x.id);
        phanHoi.F4.setText(dsht.get(1).gmail);
        phanHoi.F5.setText(dsht.get(1).thongTinHT);
        phanHoi.setVisible(true);
    }//GEN-LAST:event_Label2MouseClicked

    private void Label3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label3MouseClicked
        HoTro hoTro = new HoTro();
        hoTro = dsht.get(0);
        PhanHoi phanHoi = new PhanHoi();
        phanHoi.F1.setText(dsht.get(2).x.name);
        phanHoi.F3.setText(dsht.get(2).x.id);
        phanHoi.F4.setText(dsht.get(2).gmail);
        phanHoi.F5.setText(dsht.get(2).thongTinHT);
        phanHoi.setVisible(true);
    }//GEN-LAST:event_Label3MouseClicked

    private void Label4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label4MouseClicked
        HoTro hoTro = new HoTro();
        hoTro = dsht.get(0);
        PhanHoi phanHoi = new PhanHoi();
        phanHoi.F1.setText(dsht.get(3).x.name);
        phanHoi.F3.setText(dsht.get(3).x.id);
        phanHoi.F4.setText(dsht.get(3).gmail);
        phanHoi.F5.setText(dsht.get(3).thongTinHT);
        phanHoi.setVisible(true);
    }//GEN-LAST:event_Label4MouseClicked

    private void Label5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label5MouseClicked
        HoTro hoTro = new HoTro();
        hoTro = dsht.get(0);
        PhanHoi phanHoi = new PhanHoi();
        phanHoi.F1.setText(dsht.get(4).x.name);
        phanHoi.F3.setText(dsht.get(4).x.id);
        phanHoi.F4.setText(dsht.get(4).gmail);
        phanHoi.F5.setText(dsht.get(4).thongTinHT);
        phanHoi.setVisible(true);        
    }//GEN-LAST:event_Label5MouseClicked

    private void Label6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label6MouseClicked
        HoTro hoTro = new HoTro();
        hoTro = dsht.get(0);
        PhanHoi phanHoi = new PhanHoi();
        phanHoi.F1.setText(dsht.get(5).x.name);
        phanHoi.F3.setText(dsht.get(5).x.id);
        phanHoi.F4.setText(dsht.get(5).gmail);
        phanHoi.F5.setText(dsht.get(5).thongTinHT);
        phanHoi.setVisible(true);       
    }//GEN-LAST:event_Label6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDSHoTro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDSHoTro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDSHoTro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDSHoTro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDSHoTro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
