/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BTL;

import javax.swing.JOptionPane;
import java.util.*;
/**
 *
 * @author txdao
 */
public class FQLTaiKhoan extends javax.swing.JFrame {
    public static String user;
    public static String pass;
    public static int kind;
    static DBEngine db = new DBEngine();
    static String fileName = "taikhoan.txt";
    static String fileName2 = "taikhoangv.txt";
    static String fileName3 = "taikhoanqtv.txt";
    static ArrayList<TaiKhoan> dstk = new ArrayList<>();
    static ArrayList<TaiKhoan> dstkgv = new ArrayList<>();
    static ArrayList<TaiKhoan> dstkqtv = new ArrayList<>();
    static ArrayList<TaiKhoan> dschung = new ArrayList<>();
    /**
     * Creates new form FQLTaiKhoan
     */
    public FQLTaiKhoan() {


        try{
            dstk = (ArrayList<TaiKhoan>)db.docFile(fileName);
            dstkgv = (ArrayList<TaiKhoan>)db.docFile(fileName2);
            dstkqtv = (ArrayList<TaiKhoan>)db.docFile(fileName3);
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(rootPane, E);
        }
        dschung.addAll(dstk);
        dschung.addAll(dstkgv);
        dschung.addAll(dstkqtv);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        userT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kindT = new javax.swing.JTextField();
        suaButton = new javax.swing.JButton();
        xoaButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Quan ly tai khoan");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {dschung.get(0).user, dschung.get(0).pass, dschung.get(0).kind},
                {dschung.get(1).user, dschung.get(1).pass, dschung.get(1).kind},
                {dschung.get(2).user, dschung.get(2).pass, dschung.get(2).kind},
                {dschung.get(3).user, dschung.get(3).pass, dschung.get(3).kind},
                {dschung.get(4).user, dschung.get(4).pass, dschung.get(4).kind},
                {dschung.get(5).user, dschung.get(5).pass, dschung.get(5).kind},
                {dschung.get(6).user, dschung.get(6).pass, dschung.get(6).kind},
                {dschung.get(7).user, dschung.get(7).pass, dschung.get(7).kind},
                {dschung.get(8).user, dschung.get(8).pass, dschung.get(8).kind},
                {dschung.get(9).user, dschung.get(9).pass, dschung.get(9).kind}
            },
            new String [] {
                "User", "Password", "Kind"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("User:");

        jLabel3.setText("Pass:");

        jLabel4.setText("Kind:");

        suaButton.setText("Sua");
        suaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaButtonActionPerformed(evt);
            }
        });

        xoaButton.setText("Xoa");
        xoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(121, 121, 121))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(userT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kindT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(suaButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(xoaButton)
                                        .addGap(56, 56, 56)
                                        .addComponent(closeButton)))))
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kindT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suaButton)
                    .addComponent(xoaButton)
                    .addComponent(closeButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void suaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaButtonActionPerformed
        TaiKhoan tk = new TaiKhoan();
        if(userT.getText().length()<1||passT.getText().length()<1||kindT.getText().length()<1){
            JOptionPane.showMessageDialog(rootPane, "Khong duoc de trong thong tin!");
            return;
        }
        if(passT.getText().length()<6){
            JOptionPane.showMessageDialog(rootPane, "Password phai tren 6 ky tu!");
            return;
        }
        try{
            if(Integer.parseInt(kindT.getText()) < 1||Integer.parseInt(kindT.getText()) > 3){
                JOptionPane.showMessageDialog(rootPane, "Kind phai tu 1 - 3!");
                return;
            }
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(rootPane, "Kind user khong hop le!");
            return;
        }
        int row = jTable1.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(rootPane, "Chon 1 tai khoan");
            return;
        }
        int check = JOptionPane.showConfirmDialog(rootPane, "Chac chan sua ?", "Thay doi thong tin", 1);
        if(check == 0){
            tk.user = userT.getText();
            tk.pass = passT.getText();
            tk.kind = Integer.parseInt(kindT.getText());
            if(row<6){
                dstk.set(row, tk);
                dschung.set(row, tk);
                try{
                    db.LuuFile(fileName, dstk);
                    JOptionPane.showMessageDialog(rootPane, "Done!");
                }
                catch(Exception E){
                    JOptionPane.showMessageDialog(rootPane, E);
                }
                this.setVisible(false);
                FQLTaiKhoan Frame = new FQLTaiKhoan();
                Frame.setVisible(true);
            }
            else if(row < 8){
                dstkgv.set(row-6, tk);
                dschung.set(row, tk);
                try{
                    db.LuuFile(fileName2, dstkgv);
                    JOptionPane.showMessageDialog(rootPane, "Done!");
                }
                catch(Exception E){
                    JOptionPane.showMessageDialog(rootPane, E);
                }
                this.setVisible(false);
                FQLTaiKhoan Frame = new FQLTaiKhoan();
                Frame.setVisible(true);
            }
            else if(row < 10){
                dstkqtv.set(row-8, tk);
                dschung.set(row, tk);
                try{
                    db.LuuFile(fileName3, dstkqtv);
                    JOptionPane.showMessageDialog(rootPane, "Done!");
                }
                catch(Exception E){
                    JOptionPane.showMessageDialog(rootPane, E);
                }
                this.setVisible(false);
                FQLTaiKhoan Frame = new FQLTaiKhoan();
                Frame.setVisible(true);
            }
        }
        else{
            return;
        }
    }//GEN-LAST:event_suaButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int k = jTable1.getSelectedRow();
        userT.setText(dschung.get(k).user);
        passT.setText(dschung.get(k).pass);
        kindT.setText(String.valueOf(dschung.get(k).kind));

    }//GEN-LAST:event_jTable1MouseClicked

    private void xoaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaButtonActionPerformed
        int row = jTable1.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(rootPane, "Chon 1 tai khoan!");
            return;
        }
        else{
            int k = JOptionPane.showConfirmDialog(rootPane, "Chac chan xoa ?", "Delete", 1);
            if(k == 0){
                dschung.remove(k);
                if(k<6){
                    dstk.remove(k);
                    return;
                }
                if(k<8){
                    dstkgv.remove(k);
                    return;
                }
                dstkqtv.remove(k);
                return;
            }
        }
    }//GEN-LAST:event_xoaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FQLTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FQLTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FQLTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FQLTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FQLTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kindT;
    private javax.swing.JTextField passT;
    private javax.swing.JButton suaButton;
    private javax.swing.JTextField userT;
    private javax.swing.JButton xoaButton;
    // End of variables declaration//GEN-END:variables
}
